import Footer from "@shared/footer";
import Navbar from "@shared/navbar";
import WithAuth from "@utils/withAuth";
import Head from "next/head";
import Image from "next/image";
import React from "react";

const categories = [
   {
      link: "/cursos/maths",
      photoURL: "/categories/matematicas.jpg",
      name: "maths",
   },
   {
      link: "/cursos/ciencias",
      photoURL: "/categories/ciencias.jpg",
      name: "ciencie",
   },
   {
      link: "/cursos/tech",
      photoURL: "/categories/tecnologia.jpg",
      name: "tech",
   },
   {
      link: "/cursos/bio",
      photoURL: "/categories/biologia.jpg",
      name: "bio",
   },
];

function Cursos() {
   return (
      <WithAuth>
         <div className="min-h-[100vh] h-full bg-lightGray flex flex-col items-center">
            <Head>
               <title>Cursos</title>
               <meta
                  name="description"
                  content="Generated by create next app"
               />
               <meta
                  name="viewport"
                  content="width=device-width, initial-scale=1"
               />
               <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="h-full mt-16 w-[70vw] max-w-2xl">
               <h2 className="text-xl font-medium">Cursos</h2>
               <div className="flex flex-col items-center w-full p-2 py-4 mb-2 bg-white rounded-xl">
                  <div className="flex w-[90%] ">
                     <input
                        type="text"
                        placeholder="Preguntale a Study Wolf"
                        className="flex w-[100%] border-b-2 outline-none border-lightBlue "
                     />
                     <span className="relative flex aspect-square rounded-full overflow-hidden min-h-[2rem] min-w-[2rem] mx-2">
                        <Image src="/lobo.jpg" alt="" fill />
                     </span>
                  </div>
               </div>
               <div className="flex flex-wrap justify-center gap-2 mb-4 overflow-hidden bg-white rounded-xl w-fit">
                  {categories.map(({ link, photoURL, name }) => (
                     <a key={name} href={link}>
                        <span className="relative flex aspect-[30/17] w-[70vw] md:w-[34vw] rounded-xl overflow-hidden">
                           <Image src={photoURL} alt={name} fill />
                        </span>
                     </a>
                  ))}
               </div>
            </div>
            <Footer />
         </div>
      </WithAuth>
   );
}

export default Cursos;
