import Footer from "@shared/footer";
import Navbar from "@shared/navbar";
import Head from "next/head";
import React from "react";

function Cursos() {
   return (
      <div className="h-[100vh] bg-lightGray flex flex-col items-center">
         <Head>
            <title>Cursos</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Navbar />
         <div>daam</div>
         <Footer />
      </div>
   );
}

export default Cursos;
