import Footer from "@shared/footer";
import Navbar from "@shared/navbar";
import WithAuth from "@utils/withAuth";
import Head from "next/head";
import Image from "next/image";
import React from "react";

function Dashboard() {
   return (
      <WithAuth>
         <div className="min-h-[100vh] h-full bg-lightGray flex flex-col items-center">
            <Head>
               <title>Inicio</title>
               <meta
                  name="description"
                  content="Generated by create next app"
               />
               <meta
                  name="viewport"
                  content="width=device-width, initial-scale=1"
               />
               <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="h-full mt-16 w-[70vw] max-w-2xl">
               <h2 className="text-xl font-medium">Retos Diarios</h2>
               <div className="p-2 mb-4 bg-white rounded-xl">
                  <p className="font-medium">
                     ¿Podrás encontrar el valor de la distancia entre A y B?
                  </p>
                  <span className="flex relative aspect-[2/1] w-[90%] mx-auto">
                     <Image src="/retodiario.jpg" alt="" fill />
                  </span>
                  <p>Comparte tu respuesta en la seccion de comentarios!</p>
               </div>
               <div className="flex flex-col items-center w-full p-2 pb-6 mb-2 bg-white rounded-xl">
                  <p>Comentarios</p>
                  <div className="flex w-[70%] ">
                     <span className="relative flex aspect-square rounded-full overflow-hidden min-h-[2rem] min-w-[2rem] mx-2">
                        <Image src="/lobo.jpg" alt="" fill />
                     </span>
                     <input
                        type="text"
                        className="flex w-[100%] border-b-2 outline-none border-lightBlue "
                     />
                  </div>
               </div>
            </div>
            <Footer />
         </div>
      </WithAuth>
   );
}

export default Dashboard;
