import Footer from "@shared/footer";
import Navbar from "@shared/navbar";
import Head from "next/head";
import Image from "next/image";
import React from "react";

function Dashboard() {
   return (
      <div className="h-[100vh] bg-lightGray flex flex-col items-center">
         <Head>
            <title>Inicio</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Navbar />
         <div className="h-full mt-24">
            <div className="bg-white w-[70vw] p-2 pb-6 rounded-xl mb-2">
               <p>Comentarios</p>
               <div className="flex">
                  <span className="relative flex aspect-square rounded-full overflow-hidden min-h-[2rem] min-w-[2rem] mx-2">
                     <Image src="/lobo.jpg" alt="" fill />
                  </span>
                  <input
                     type="text"
                     className="flex w-[70%] border-b-2 outline-none border-lightBlue mx-auto"
                  />
               </div>
            </div>
         </div>
         <Footer />
      </div>
   );
}

export default Dashboard;
