import Head from "next/head";
import Link from "next/link";

export default function Home() {
   return (
      <div className="flex flex-col items-center h-[100vh] w-full">
         <Head>
            <title>Study Wolf</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <nav className="fixed flex bg-[#F3F3F3] rounded-lg justify-start left-0 z-10">
            <Link href="/registro" className="p-3">
               Registrarse
            </Link>
            <Link href="/login" className="p-3">
               Iniciar sesion
            </Link>
         </nav>

         <div className="relative flex justify-center w-full">
            <span className=" h-[100vh] flex justify-center items-center">
               <img
                  src="/fondo.jpg"
                  alt=""
                  className="absolute left-0 top-0 flex object-cover h-full w-[100vw] -z-10"
               />
               <h1 className="text-3xl font-bold text-white">
                  <Link href="/dashboard">Bienvenido a Study wolf</Link>
               </h1>
            </span>
         </div>

         <div className="flex flex-col items-center max-w-[90vw] w-[70ch] pb-4">
            <h2 className="my-2 text-2xl font-bold">¿Que es study wolf?</h2>

            <p>
               Es una plataforma de cursos online interactiva orientada a dar
               clases online sobre variados temas del ámbito académico con un
               amplio soporte a los estudiantes
            </p>

            <h2 className="my-2 text-2xl font-bold">
               ¿Por qué aprender aquí?{" "}
            </h2>

            <p>
               Debido que muchos autodidactas novatos de la web detienen su
               progreso al no tener claro que camino deben tomar o solo pierden
               el interés por aburrimiento al solo encontrarse con una forma de
               aprender en la que domina la pasividad en el aprendizaje esta
               página web pretende ofrecer una guía para las personas que desean
               aprender más sobre los temas que necesiten en la que aparte se
               ofrezca una interfaz interactiva llena de talleres o actividades
               para mantener y aumentar la motivación por el aprendizaje
            </p>
         </div>
      </div>
   );
}
